name: CI

on:
  push:
    branches:
      - main # Change this to your main branch name if needed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the Node.js version you need

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Check for vulnerabilities
        run: npm audit

      - name: Run npm ci
        run: npm ci

      # Add more steps here for your specific build and test process

      - name: Cleanup
        run: npm cache clean --force

# Add more jobs or customize the steps based on your project's requirements
